-- =============================================
-- DATOS DE PRUEBA — visitapurranque.cl
-- Columnas ajustadas al schema real de la BD
-- =============================================

-- Fichas de atractivos turísticos reales
-- Nota: tabla fichas usa latitud/longitud, descripcion, activo/eliminado (no estado)
INSERT INTO fichas (categoria_id, nombre, slug, descripcion_corta, descripcion, direccion, latitud, longitud, telefono, whatsapp, verificado, destacado, activo, eliminado, created_at, updated_at) VALUES
(1, 'Parque Mapu Lahual', 'parque-mapu-lahual', 'Red de parques indígenas con bosque de alerce milenario', 'El Parque Mapu Lahual es una red de áreas protegidas administradas por comunidades Huilliche en la costa de Purranque. Cuenta con senderos a través de bosques de alerce milenario, arrayán y olivillo costero. Es un destino imperdible para el ecoturismo y turismo comunitario.', 'Costa de Purranque, sector Manquemapu', -40.6500000, -73.7200000, '+56912345678', '56912345678', 1, 1, 1, 0, NOW(), NOW()),
(1, 'Caleta Manquemapu', 'caleta-manquemapu', 'Caleta de pescadores artesanales en la costa de Purranque', 'Manquemapu es una pequeña caleta de pescadores ubicada en la costa sur de la comuna de Purranque. Accesible por camino de ripio (2-3 horas), ofrece paisajes vírgenes, gastronomía marina y la experiencia de una comunidad costera auténtica.', 'Manquemapu, Costa de Purranque', -40.5800000, -73.7400000, '+56912345679', '56912345679', 1, 1, 1, 0, NOW(), NOW()),
(1, 'Bahía San Pedro', 'bahia-san-pedro', 'Bahía prístina con playas y bosque nativo', 'La Bahía San Pedro es uno de los secretos mejor guardados de la costa de Purranque. Con playas de arena oscura rodeadas de bosque nativo, ofrece un paisaje único para quienes buscan naturaleza sin intervención.', 'Bahía San Pedro, Costa de Purranque', -40.6200000, -73.7600000, NULL, NULL, 0, 0, 1, 0, NOW(), NOW()),
(3, 'Plaza de Armas de Purranque', 'plaza-de-armas-purranque', 'Centro cívico y punto de encuentro de la ciudad', 'La Plaza de Armas de Purranque es el corazón de la ciudad. Rodeada de comercio, servicios y la Iglesia Parroquial, es el punto de partida ideal para conocer la zona urbana.', 'Centro de Purranque', -40.9117000, -73.1347000, NULL, NULL, 1, 0, 1, 0, NOW(), NOW()),
(3, 'Iglesia Parroquial San Sebastián', 'iglesia-san-sebastian', 'Templo histórico y sede de la fiesta patronal', 'La Iglesia de San Sebastián es el principal templo de Purranque y sede de la tradicional Fiesta de San Sebastián cada 20 de enero. Su arquitectura de madera es representativa de las iglesias del sur de Chile.', 'Calle Señoret, Purranque', -40.9110000, -73.1340000, NULL, NULL, 1, 1, 1, 0, NOW(), NOW()),
(5, 'Feria Costumbrista de Purranque', 'feria-costumbrista-purranque', 'Celebración anual de tradiciones campesinas', 'La Feria Costumbrista reúne lo mejor de la tradición rural de Purranque: gastronomía típica, artesanía, música folclórica y juegos campesinos.', 'Sector rural, Purranque', -40.9200000, -73.2000000, NULL, NULL, 0, 0, 1, 0, NOW(), NOW()),
(2, 'Cascadas del Río Chanleufú', 'cascadas-rio-chanle', 'Saltos de agua en entorno de bosque nativo', 'Las cascadas del río Chanleufú ofrecen un espectáculo natural rodeado de bosque nativo. Accesible por sendero de dificultad media, ideal para fotografía y contemplación.', 'Sector Chanleufú, Purranque', -40.8500000, -73.3000000, NULL, NULL, 0, 1, 1, 0, NOW(), NOW()),
(6, 'Hostal Don Luis', 'hostal-don-luis', 'Hospedaje céntrico con atención familiar', 'Hostal Don Luis ofrece habitaciones cómodas en el centro de Purranque. Ideal para viajeros que buscan una base para explorar la comuna. Incluye desayuno y estacionamiento.', 'Calle Eleuterio Ramírez 520, Purranque', -40.9120000, -73.1350000, '+56965432100', '56965432100', 1, 0, 1, 0, NOW(), NOW());

-- Eventos
-- Nota: tabla eventos usa titulo (no nombre), lugar (no ubicacion), latitud/longitud, activo/eliminado (no estado/tipo)
INSERT INTO eventos (titulo, slug, descripcion, fecha_inicio, fecha_fin, lugar, latitud, longitud, destacado, activo, eliminado, created_at, updated_at) VALUES
('Fiesta de San Sebastián 2026', 'fiesta-san-sebastian-2026', 'Tradicional fiesta patronal de Purranque con procesión, misa, feria gastronómica y actividades culturales.', '2026-01-20 09:00:00', '2026-01-20 23:00:00', 'Iglesia San Sebastián, Purranque', -40.9110000, -73.1340000, 1, 1, 0, NOW(), NOW()),
('Feria Gastronómica de Verano', 'feria-gastronomica-verano-2026', 'Muestra gastronómica con productos locales: quesos, sidra, empanadas, asado al palo y dulces tradicionales.', '2026-02-15 11:00:00', '2026-02-15 20:00:00', 'Plaza de Armas, Purranque', -40.9117000, -73.1347000, 1, 1, 0, NOW(), NOW()),
('Trekking Mapu Lahual — Temporada 2026', 'trekking-mapu-lahual-2026', 'Temporada de trekking guiado por senderos ancestrales en bosque de alerce milenario. Guías locales huilliche.', '2026-12-01 08:00:00', '2027-03-31 18:00:00', 'Parque Mapu Lahual, Costa de Purranque', -40.6500000, -73.7200000, 0, 1, 0, NOW(), NOW()),
('Aniversario de Purranque 2026', 'aniversario-purranque-2026', 'Celebración del aniversario de la comuna con desfile, actividades culturales y show artístico.', '2026-10-15 10:00:00', '2026-10-17 23:00:00', 'Centro de Purranque', -40.9117000, -73.1347000, 1, 1, 0, NOW(), NOW());

-- Blog posts
-- Nota: tabla blog_posts usa imagen_portada, autor_id (FK), tiene estado enum y publicado_at
INSERT INTO blog_posts (titulo, slug, extracto, contenido, imagen_portada, tipo, estado, publicado_at, destacado, tiempo_lectura, created_at, updated_at) VALUES
('Guía completa para visitar la costa de Purranque', 'guia-costa-purranque', 'Todo lo que necesitas saber para planificar tu viaje a Manquemapu, San Pedro y Mapu Lahual.', 'La costa de Purranque es uno de los destinos más auténticos del sur de Chile.\n\nCómo llegar: Desde Purranque, tomar la ruta U-910 hacia la costa. El camino es de ripio y toma entre 2 y 3 horas en vehículo 4x4. También existe un bus subsidiado.\n\nQué llevar: Ropa impermeable, zapatos de trekking, protector solar y efectivo (no hay cajeros en la costa).\n\nDónde dormir: Hospedajes familiares en Manquemapu con alimentación incluida. Camping en las caletas costeras.\n\nActividades: Trekking en Mapu Lahual, pesca artesanal, observación de fauna marina, fotografía de paisajes.', NULL, 'guia', 'publicado', NOW(), 1, 2, NOW(), NOW()),
('5 platos típicos que debes probar en Purranque', 'platos-tipicos-purranque', 'Desde el asado al palo hasta la sopaipilla pasada, descubre los sabores del sur.', 'La gastronomía de Purranque refleja su identidad campesina y costera.\n\n1. Asado al palo: Cordero o chivo cocinado lentamente sobre brasas.\n2. Curanto: Preparación ancestral con mariscos, carnes y papas.\n3. Milcao: Preparación de papa rallada típica del sur.\n4. Empanadas de horno: Rellenas de pino con huevo.\n5. Sopaipillas pasadas: Con chancaca caliente, ideales para días de lluvia.', NULL, 'articulo', 'publicado', NOW(), 1, 1, NOW(), NOW()),
('La historia de los alerces milenarios de Mapu Lahual', 'alerces-mapu-lahual', 'Conoce la fascinante historia de los árboles más antiguos de Sudamérica.', 'Los alerces (Fitzroya cupressoides) del Parque Mapu Lahual son algunos de los árboles más antiguos del planeta, con ejemplares que superan los 3.000 años de edad.\n\nEstos gigantes del bosque valdiviano son protegidos por las comunidades Huilliche que habitan la costa de Purranque desde tiempos ancestrales.\n\nEl alerce fue declarado Monumento Natural en 1976, prohibiéndose su tala. Hoy, los senderos de Mapu Lahual permiten caminar entre estos colosos en un entorno de bosque prístino.', NULL, 'articulo', 'publicado', NOW(), 0, 1, NOW(), NOW());

-- Reseñas de prueba
-- Nota: tabla resenas usa rating (no calificacion), tiene tipo_experiencia
-- IMPORTANTE: Los ficha_id dependen del auto_increment actual.
-- Si fichas empieza en id=1: usar 1,1,2,5,8
-- Si fichas empieza en id=7 (como en dev): usar 7,7,8,11,14
-- Ajustar según corresponda antes de ejecutar.
INSERT INTO resenas (ficha_id, nombre, email, rating, tipo_experiencia, comentario, estado, created_at) VALUES
(7, 'María González', 'maria@example.com', 5, 'trekking', 'Increíble experiencia. Los bosques de alerce son impresionantes. Los guías locales son muy conocedores.', 'aprobada', NOW()),
(7, 'Carlos Muñoz', 'carlos@example.com', 4, 'trekking', 'Hermoso lugar pero el camino es muy largo y difícil. Llevar vehículo 4x4 obligatorio.', 'aprobada', NOW()),
(8, 'Ana Pérez', 'ana@example.com', 5, 'gastronomia', 'La caleta más auténtica que he visitado. Los mariscos frescos son espectaculares.', 'aprobada', NOW()),
(11, 'Pedro Soto', 'pedro@example.com', 4, 'visita_cultural', 'Hermosa iglesia de madera. Vale la pena visitarla durante la Fiesta de San Sebastián.', 'aprobada', NOW()),
(14, 'Laura Díaz', 'laura@example.com', 3, 'alojamiento', 'Hospedaje sencillo pero limpio y con buena atención. El desayuno es abundante.', 'aprobada', NOW());

-- Preguntas frecuentes
INSERT INTO faq (pregunta, respuesta, categoria, orden, activo) VALUES
('Como llegar a Purranque?', 'Purranque se encuentra a 948 km al sur de Santiago. Puedes llegar en avion hasta Osorno (aeropuerto Canal Bajo) o Puerto Montt (El Tepual) y luego tomar un bus o auto por la Ruta 5 Sur. En bus, las principales empresas (Pullman Bus, Cruz del Sur, Buses ETM) tienen recorridos diarios desde Santiago y ciudades intermedias.', 'general', 1, 1),
('Cual es la mejor epoca para visitar Purranque?', 'La mejor epoca es entre diciembre y marzo (verano), cuando las temperaturas son mas agradables (15-25 C) y hay menos lluvias. Sin embargo, cada estacion tiene su encanto: en otono los bosques se tiñen de colores, y en invierno puedes disfrutar de termas y gastronomia local junto a la chimenea.', 'turismo', 2, 1),
('Que atractivos turisticos tiene Purranque?', 'Purranque ofrece cascadas, lagos, bosques nativos de alerces milenarios en el Parque Mapu Lahual, playas en la costa como Bahia Mansa, termas naturales, y una rica tradicion gastronomica y cultural. Tambien hay fiestas costumbristas, ferias gastronomicas y trekking en temporada.', 'turismo', 3, 1),
('Donde puedo alojarme en Purranque?', 'Existen diversas opciones de alojamiento: hostales, cabañas, camping y turismo rural. Puedes encontrar opciones en nuestro directorio de atractivos buscando por la categoria correspondiente.', 'servicios', 4, 1),
('Se puede hacer trekking en la zona?', 'Si, la zona ofrece excelentes rutas de trekking, especialmente en el Parque Mapu Lahual con sus bosques de alerces milenarios. La temporada ideal es de octubre a abril. Se recomienda ir con guia local para las rutas mas exigentes.', 'turismo', 5, 1),
('Como puedo agregar mi negocio al directorio?', 'Puedes contactarnos a traves del formulario de contacto o escribirnos directamente. Evaluaremos tu solicitud y te informaremos sobre los planes disponibles para aparecer en nuestro directorio de atractivos turisticos.', 'servicios', 6, 1),
('El sitio es gratuito para los visitantes?', 'Si, el acceso a toda la informacion del sitio es completamente gratuito para los visitantes. Nuestro objetivo es promover el turismo en Purranque y facilitar la planificacion de tu viaje.', 'general', 7, 1),
('Puedo dejar una resena de un lugar que visite?', 'Si, en cada ficha de atractivo turistico encontraras un formulario para dejar tu resena. Tu opinion es muy valiosa para otros viajeros y para los emprendedores locales. Las resenas son moderadas antes de publicarse.', 'general', 8, 1);
